#!/usr/bin/env python3
"""Concatenate static/game/src/*.js into static/game/game.js.

Used both as a CLI (`python3 build_game_js.py`) and imported by `server.py`
so the bundle is rebuilt on every server start.
"""

import subprocess
from pathlib import Path

SRC_DIR = Path(__file__).resolve().parent / "static" / "game" / "src"
OUT = Path(__file__).resolve().parent / "static" / "game" / "game.js"
HEADER = (
    "// AUTOGENERATED by build_game_js.py from static/game/src/*.js "
    "— do not edit directly.\n\n"
)


def build(check_syntax=True, verbose=True):
    """Concatenate sources and overwrite the bundle. Returns the output Path."""
    files = sorted(SRC_DIR.glob("*.js"))
    if not files:
        raise RuntimeError(f"No .js files in {SRC_DIR}")

    parts = [HEADER]
    for f in files:
        parts.append(f"// ===== {f.name} =====\n")
        text = f.read_text()
        parts.append(text)
        if not text.endswith("\n"):
            parts.append("\n")

    out_text = "".join(parts)
    OUT.write_text(out_text)

    if verbose:
        line_count = out_text.count("\n")
        print(f"[build_game_js] wrote {OUT} ({line_count} lines, {len(out_text)} bytes from {len(files)} files)")

    if check_syntax:
        try:
            check = subprocess.run(
                ["node", "--check", str(OUT)],
                capture_output=True,
                text=True,
            )
        except FileNotFoundError:
            if verbose:
                print("[build_game_js] node not found, skipping syntax check")
        else:
            if check.returncode != 0:
                raise RuntimeError(check.stderr or check.stdout or "node --check failed")

    return OUT


def main():
    try:
        build()
    except RuntimeError as exc:
        raise SystemExit(str(exc))


if __name__ == "__main__":
    main()
