TRUNCATE TABLE vckonline.events;
INSERT INTO vckonline.events (id_events,name,roll_match1,roll_effect,has_roll_effect,is_monster,has_activation_effect,has_passive_effect,strength_cost,magic_cost,monster_type,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,roll_effect_text,special_reward_text,activation_effect_text,passive_effect_text,activation_effect,passive_effect,expansion) VALUES
	 (1,'Corrupted Cleric',1,'add_slay_cost m 1',1,1,0,0,2,4,'Titan',2,3,0,2,0,NULL,'Add 1 Magic to any Monster in the center stacks.','','','',NULL,NULL,'base'),
	 (2,'Giant Leech',2,'all_lose s 1',1,1,0,0,10,1,'Titan',4,0,0,5,0,NULL,'All players lose 1 Strength.','','','',NULL,NULL,'base'),
	 (3,'Bat Swarm',3,'add_slay_cost s 1',1,1,0,0,6,0,'Minion',2,0,0,0,1,'count owned_monsters g 1','Add 1 Strength to any Monster in the center stacks.','Gain 1 Gold for each owned Monster.','','',NULL,NULL,'base'),
	 (4,'Sorcerer',4,'all_lose m 1',1,1,0,0,1,5,'Titan',1,0,0,0,1,'count owned_monsters m 1','All players lose 1 Magic.','Gain 1 Magic for each owned Monster.','','',NULL,NULL,'base'),
	 (5,'Mimic',5,'add_slay_cost g 1',1,1,0,0,3,3,'Minion',2,5,0,0,0,NULL,'Add 1 Gold to any Monster in the center stacks.','','','',NULL,NULL,'base'),
	 (6,'Kobold Thieves',6,'all_lose g 1',1,1,0,0,6,0,'Minion',1,7,0,0,0,NULL,'All players lose 1 Gold.','','','',NULL,NULL,'base'),
	 (7,'Bog Witch''s Proposal',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players may immediately pay 3 Magic for 2 Victory Points.','','all_may self_convert pay=m:3 gain=v:2',NULL,'kingsguard'),
	 (8,'Gift from the Fae',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','The Active player immediately gains 2 Magic. All other players gain 1 Magic.','','active_gain m 2 + others_gain m 1',NULL,'kingsguard'),
	 (9,'Quell Rebellion',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players may immediately pay 3 Strength for 2 Victory Points.','','all_may self_convert pay=s:3 gain=v:2',NULL,'kingsguard'),
	 (10,'Recruit the King''s Guard',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','Immediately place the King''s Guard Citizen stack into play.','','place_kings_guard',NULL,'kingsguard');
INSERT INTO vckonline.events (id_events,name,roll_match1,roll_effect,has_roll_effect,is_monster,has_activation_effect,has_passive_effect,strength_cost,magic_cost,monster_type,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,roll_effect_text,special_reward_text,activation_effect_text,passive_effect_text,activation_effect,passive_effect,expansion) VALUES
	 (11,'Twin Bandits of Pyth',-1,NULL,0,0,0,1,0,0,NULL,0,0,0,0,0,NULL,'','','','During any Roll Phase, when doubles are rolled all players lose 1 Gold, 1 Strength, and 1 Magic.',NULL,'roll.on_event doubles all_lose g 1 + all_lose s 1 + all_lose m 1','kingsguard'),
	 (12,'Blood Plague',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,'','','','All players immediately lose 2 Strength.','','all_lose s 2',NULL,'undeadsamurai'),
	 (13,'Queen''s Day Festival',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,'','','','The Active player immediately gains 2 Gold. All other players gain 1 Gold. ','','active_gain g 2 + others_gain g 1',NULL,'undeadsamurai'),
	 (14,'Tax Collection',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,'','','','All players may immediately pay 3 Gold for 2 Victory Points.','','all_may self_convert pay=g:3 gain=v:2',NULL,'undeadsamurai'),
	 (15,'Tribute to the King',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,'','','','All players may immediately pay 1 Gold, 1 Strength, and 1 Magic for 2 Victory Points.','','all_may self_convert pay=g:1,s:1,m:1 gain=v:2',NULL,'undeadsamurai'),
	 (16,'Undead Samurai Lord',-1,NULL,0,1,1,0,5,5,'Boss',4,0,0,0,1,'count area "Undead Samurai" v 1','','Gain 1 Victory Point for each monster you own from the Undead Samurai Area.','Place Undead Samurai cards on the center stacks according to the Undead Samurai event rules.','','seq all_must place_reserve_monster pool=undead_samurai',NULL,'undeadsamurai'),
	 (17,'A Call To Arms',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players may immediately banish a Soldier Citizen for 3 Victory Points.','','all_may banish_owned_citizen role=soldier gain=v:3',NULL,'flamesandfrost'),
	 (18,'The Wizards of Nae',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','The Active player may immediately pay 3 Magic for an additional action. ','','active_may gain_action pay=m:3',NULL,'flamesandfrost'),
	 (19,'Support The Empire',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players may immediately pay 5 Wild for 3 Victory Points.','','all_may self_convert pay=wild:5 gain=v:3',NULL,'flamesandfrost'),
	 (20,'Curse of The North',-1,NULL,0,0,0,1,0,0,NULL,0,0,0,0,0,NULL,'','','','During any Roll Phase, when doubles are rolled all players lose 3 Magic.',NULL,'roll.on_event doubles all_lose m 3','flamesandfrost');
INSERT INTO vckonline.events (id_events,name,roll_match1,roll_effect,has_roll_effect,is_monster,has_activation_effect,has_passive_effect,strength_cost,magic_cost,monster_type,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,roll_effect_text,special_reward_text,activation_effect_text,passive_effect_text,activation_effect,passive_effect,expansion) VALUES
	 (21,'The Key and Blade',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','The Active player immediately loses 3 Gold. All other players lose 1 Gold.','','active_lose g 3 + others_lose g 1',NULL,'flamesandfrost'),
	 (22,'A Betrayal of Bonds',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players must immediately flip a Citizen.','','all_must flip_citizen',NULL,'flamesandfrost'),
	 (23,'Alms for the Poor',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','In turn order, all players must immediately pay 2 Wild to a player of their choice, if able.','','seq all_must pay_to_chosen pay=wild:2',NULL,'shadowvale'),
	 (24,'Blessed Lands',-1,NULL,0,0,0,1,0,0,NULL,0,0,0,0,0,NULL,'','','','For the rest of the game, all Domains cost 2 Gold less to build.',NULL,'grant_all action.blessedlands','shadowvale'),
	 (25,'Dark Lord Rising',-1,NULL,0,0,0,1,0,0,NULL,0,0,0,0,0,NULL,'','','','For the rest of the game, all Monsters cost 1 Magic more to slay.',NULL,'grant_all action.darklordrising','shadowvale'),
	 (26,'Golden Idol',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','The Active player may immediately gain 2 Gold or all players may gain 4 Magic.','','active_choose self_gain:g:2 | all_gain:m:4',NULL,'shadowvale'),
	 (27,'Good Omen',-1,NULL,0,0,0,1,0,0,NULL,0,0,0,0,0,NULL,'','','','During any Roll Phase, when doubles are rolled, all players gain 1 Gold, 1 Strength, and 1 Magic.',NULL,'roll.on_event doubles all_gain g 1 + all_gain s 1 + all_gain m 1','shadowvale'),
	 (28,'Night Terror',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','In turn order, each player must immediately Banish a Citizen from the center stacks.','','seq all_must banish_center_citizen',NULL,'shadowvale'),
	 (29,'Untapped Potential',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','All players immediately gain 1 Magic for each Citizen they own.','','all_gain_per_owned gain=m:1 per=citizen',NULL,'shadowvale'),
	 (30,'Worthy Sacrifice',-1,NULL,0,0,1,0,0,0,NULL,0,0,0,0,0,NULL,'','','In turn order, each player may immediately Banish one of their Citizens to gain 3 Victory Points.','','seq all_may banish_owned_citizen gain=v:3',NULL,'shadowvale');
INSERT INTO vckonline.events (id_events,name,roll_match1,roll_effect,has_roll_effect,is_monster,has_activation_effect,has_passive_effect,strength_cost,magic_cost,monster_type,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,roll_effect_text,special_reward_text,activation_effect_text,passive_effect_text,activation_effect,passive_effect,expansion) VALUES
	 (31,'Flaming Devourer',4,'banish_center_citizen optional',1,1,0,0,14,3,'Boss',5,10,0,0,0,NULL,'When a 4 is rolled, the Active Player may Banish (remove from the game) 1 Citizen card from the Center Stacks.','','','',NULL,NULL,'crimsonseas'),
	 (32,'Ghost Ship',-1,'add_self_gold_pool 1',1,1,1,0,6,6,'Boss',5,0,0,0,1,'gain_self_gold_pool','At the end of each player’s Roll Phase, the Active Player must place 1 Gold from their supply onto the Ghost Ship.','When a player slays this Monster they gain all the Gold tokens on the this card as their Reward.','When revealed, the Active Player must place 1 Gold from their supply onto the Ghost Ship.','','add_self_gold_pool 1',NULL,'crimsonseas'),
	 (33,'Giants of Ostendaar',5,'banish_center_domain optional',1,1,0,0,10,2,'Titan',3,0,0,0,1,'<domains>','When a 5 is rolled, the Active Player may Banish (remove from the game) 1 face-up Domain card from the Center Stacks. Reveal the next Domain by flipping it over if there is still a Domain card in the stack.','Take a Domain.','','',NULL,NULL,'crimsonseas'),
	 (34,'Leviathan',6,'add_self_slay_cost s 1 max=10',1,1,0,0,6,16,'Boss',6,0,0,0,1,'count owned_monsters v 1','When a 6 is rolled, add 1 Strength token from the Bank to the top of the Leviathan card. During the Action Phase, the total amount of Strength needed to Slay this Monster is equal to its printed value plus the amount of Strength tokens on the card. The maximum amount of Strength tokens allowed on this card is 10.','Gain 1 Victory Point for every owned Monster.','','',NULL,NULL,'crimsonseas'),
	 (35,'Pirate Blockade',-1,'block_recruit_matching_roll',1,1,0,0,9,3,'Minion',4,0,0,0,1,'choose g 4 p 2','During the Action Phase, the values of each dice and the sum of both dice rolled during the Roll Phase may not be gained. This includes the Recruit a Citizen action, and any instances where a Monster or Domain card would allow a player to gain that Citizen.','Gain 4 Gold or 2 Maps.','','',NULL,NULL,'crimsonseas'),
	 (36,'Skeleton Army',3,'flip_citizen targeted optional',1,1,0,0,7,5,'Minion',4,0,0,0,1,'choose g 4 t 1','When a 3 is rolled, the Active Player may flip 1 Citizen card from an Opponents tableau. The card is inactive for the rest of the game. At the end of the game, the player flips the card face up and counts it for end-game points as normal.','Gain 4 Gold or 1 Tome.','','',NULL,NULL,'crimsonseas');
