TRUNCATE TABLE vckonline.monsters;
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (1,'Goblin','Hills','Minion',1,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1',''),
	 (2,'Goblin','Hills','Minion',2,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1',''),
	 (3,'Goblin','Hills','Minion',3,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1',''),
	 (4,'Goblin Mage','Hills','Titan',4,3,0,2,0,0,0,1,'choose g 1 m 1',NULL,NULL,0,'base1','Gain 1 Gold or 1 Magic.'),
	 (5,'Goblin Mage','Hills','Titan',5,3,0,2,0,0,0,1,'choose g 1 m 1',NULL,NULL,1,'base1','Gain 1 Gold or 1 Magic.'),
	 (6,'Goblin Bomber','Hills','Warden',6,5,0,3,0,0,0,1,'choose g 2 m 2  s 2',NULL,NULL,0,'base1','Gain 2 Wild.'),
	 (7,'Goblin King','Hills','Boss',7,6,0,4,0,0,0,1,'count area Hills g 1',NULL,NULL,0,'base1','Gain 1 Gold for each Hills Monster you own.'),
	 (8,'Skeleton','Ruins','Minion',1,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1',''),
	 (9,'Skeleton','Ruins','Minion',2,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1',''),
	 (10,'Skeleton','Ruins','Minion',3,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (11,'Flaming Skeleton','Ruins','Titan',4,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'base1',''),
	 (12,'Flaming Skeleton','Ruins','Titan',5,5,0,3,1,0,1,0,NULL,NULL,NULL,1,'base1',''),
	 (13,'Death Knight','Ruins','Warden',6,7,0,1,0,0,5,0,NULL,NULL,NULL,0,'base1',''),
	 (14,'Skeleton King','Ruins','Boss',7,8,0,4,0,0,0,1,'count area Ruins g 2',NULL,NULL,0,'base1','Gain 2 Gold for each Ruins Monster you own.'),
	 (15,'Treant','Forest','Minion',1,3,0,1,1,0,1,0,NULL,NULL,NULL,0,'base1',''),
	 (16,'Treant','Forest','Minion',2,3,0,1,1,0,1,0,NULL,NULL,NULL,0,'base1',''),
	 (17,'Treant','Forest','Minion',3,3,0,1,1,0,1,0,NULL,NULL,NULL,1,'base1',''),
	 (18,'Bane Spider','Forest','Beast',4,6,0,2,0,0,0,1,'choose g 3 <citizens where name==Knight>',NULL,NULL,0,'base1','Gain 3 Gold, or take a Knight.'),
	 (19,'Bane Spider','Forest','Beast',5,6,0,2,0,0,0,1,'choose g 3 <citizens where name==Knight>',NULL,NULL,0,'base1','Gain 3 Gold, or take a Knight.'),
	 (20,'Ettercap','Forest','Warden',6,3,5,2,0,0,0,1,'choose <citizens where gold_cost<=2>',NULL,NULL,0,'base1','Take a Citizen that costs 2 Gold or less.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (21,'Spider Queen','Forest','Boss',7,10,3,5,0,0,0,1,'choose <count area Forest g 2> <citizens + v 1>',NULL,NULL,0,'base1','Gain 2 Gold for each Forest Monster you own, or take a Citizen and gain 1 Victory Point.'),
	 (22,'Owlbear','Valley','Beast',1,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1',''),
	 (23,'Owlbear','Valley','Beast',2,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1',''),
	 (24,'Owlbear','Valley','Beast',3,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1',''),
	 (25,'Giant','Valley','Titan',4,8,0,3,1,0,2,0,NULL,NULL,NULL,0,'base1',''),
	 (26,'Giant','Valley','Titan',5,8,0,3,1,0,2,0,NULL,NULL,NULL,1,'base1',''),
	 (27,'Satyr Mage','Valley','Warden',6,5,5,3,0,0,0,1,'choose g 5 m 5 s 5',NULL,NULL,0,'base1','Gain 5 Wild.'),
	 (28,'Troll','Valley','Boss',7,12,0,6,0,0,0,1,'count area Valley m 2',NULL,NULL,0,'base1','Gain 2 Magic for each Valley Monster you own.'),
	 (29,'Dire Bear','Mountains','Beast',1,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,0,'base1','Gain 2 Gold or 2 Magic.'),
	 (30,'Dire Bear','Mountains','Beast',2,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,0,'base1','Gain 2 Gold or 2 Magic.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (31,'Dire Bear','Mountains','Beast',3,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,1,'base1','Gain 2 Gold or 2 Magic.'),
	 (32,'Orc Warrior','Mountains','Minion',4,9,0,3,0,0,0,1,'choose <citizens where gold_cost<=3>',NULL,NULL,0,'base1','Take a Citizen that costs 3 Gold or less.'),
	 (33,'Orc Warrior','Mountains','Minion',5,9,0,3,0,0,0,1,'choose <citizens where gold_cost<=3>',NULL,NULL,0,'base1','Take a Citizen that costs 3 Gold or less.'),
	 (34,'Orc Batrider','Mountains','Warden',6,12,0,5,0,0,0,1,'choose <citizens>',NULL,NULL,0,'base1','Take a Citizen.'),
	 (35,'Orc Chieftain','Mountains','Boss',7,14,0,6,0,0,0,1,'count area Mountains g 2',NULL,NULL,0,'base1','Gain 2 Gold for each Mountains Monster you own.'),
	 (36,'Gargoyle','Barrens','Minion',1,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2',''),
	 (37,'Gargoyle','Barrens','Minion',2,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2',''),
	 (38,'Gargoyle','Barrens','Minion',3,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2',''),
	 (39,'Gargoyle','Barrens','Minion',4,1,0,1,0,0,1,0,NULL,NULL,NULL,1,'base2',''),
	 (40,'Wraith','Barrens','Titan',5,4,3,3,0,0,0,1,'choose <citizens where gold_cost<=2>',NULL,NULL,0,'base2','Take a Citizen that costs 2 Gold or less.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (41,'Flesh Golem','Barrens','Warden',6,8,0,1,0,0,5,0,NULL,NULL,NULL,0,'base2',''),
	 (42,'Witch Queen','Barrens','Boss',7,5,4,5,0,0,0,1,'count area Barrens m 1',NULL,NULL,0,'base2','Gain 1 Magic for each Barrens Monster you own.'),
	 (43,'Gelatinous Cube','Swamp','Minion',1,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2',''),
	 (44,'Gelatinous Cube','Swamp','Minion',2,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2',''),
	 (45,'Gelatinous Cube','Swamp','Minion',3,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2',''),
	 (46,'Gelatinous Cube','Swamp','Minion',4,4,1,3,2,0,0,0,NULL,NULL,NULL,1,'base2',''),
	 (47,'Basilisk','Swamp','Beast',5,6,3,4,0,0,0,1,'choose g 3 m 3',NULL,NULL,0,'base2','Gain 3 Gold or 3 Magic.'),
	 (48,'Swamp Witch','Swamp','Warden',6,1,8,3,0,5,0,0,NULL,NULL,NULL,0,'base2',''),
	 (49,'Swamp Dragon','Swamp','Boss',7,10,4,6,0,0,0,1,'count area Swamp m 2',NULL,NULL,0,'base2','Gain 2 Magic for each Swamp Monster you own.'),
	 (50,'Kobolds','Cavern','Minion',1,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (51,'Kobolds','Cavern','Minion',2,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2',''),
	 (52,'Kobolds','Cavern','Minion',3,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2',''),
	 (53,'Kobolds','Cavern','Minion',4,5,1,3,2,0,1,0,NULL,NULL,NULL,1,'base2',''),
	 (54,'Gold Golem','Cavern','Titan',5,7,3,4,5,0,0,0,NULL,NULL,NULL,0,'base2',''),
	 (55,'Dragonkin','Cavern','Warden',6,6,6,4,3,0,3,0,NULL,NULL,NULL,0,'base2',''),
	 (56,'Red Dragon','Cavern','Boss',7,12,6,7,0,0,0,1,'count area Cavern g 3',NULL,NULL,0,'base2','Gain 3 Gold for each Cavern Monster you own.'),
	 (57,'Undead Samurai','Undead Samurai','Minion',1,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai',''),
	 (58,'Undead Samurai','Undead Samurai','Minion',2,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai',''),
	 (59,'Undead Samurai','Undead Samurai','Minion',3,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai',''),
	 (60,'Undead Samurai','Undead Samurai','Minion',4,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (61,'Undead Samurai','Undead Samurai','Minion',5,3,0,1,0,0,3,0,NULL,NULL,NULL,1,'undeadsamurai',''),
	 (62,'Undead Samurai Rider','Undead Samurai','Warden',6,3,3,3,0,0,0,1,'flip_citizen targeted',NULL,NULL,0,'undeadsamurai','Flip a Citizen on an opponent''s tableau face-down.'),
	 (63,'Undead Samurai Lord','Undead Samurai','Boss',7,5,5,4,0,0,0,1,'count area "Undead Samurai" m 1',NULL,NULL,0,'undeadsamurai','Gain 1 Magic for each Undead Samurai Monster you own.'),
	 (64,'Lava Hound','Volcano','Beast',1,7,1,3,0,0,0,1,'choose g 3 v 1',NULL,NULL,0,'flamesandfrost','Gain 3 Gold or 1 Victory Point.'),
	 (65,'Lava Hound','Volcano','Beast',2,7,1,3,0,0,0,1,'choose g 3 v 1',NULL,NULL,0,'flamesandfrost','Gain 3 Gold or 1 Victory Point.'),
	 (66,'Lava Hound','Volcano','Beast',3,7,1,3,0,0,0,1,'choose g 3 v 1',NULL,NULL,0,'flamesandfrost','Gain 3 Gold or 1 Victory Point.'),
	 (67,'Salamander','Volcano','Titan',4,8,4,3,2,0,2,0,NULL,NULL,NULL,0,'flamesandfrost',''),
	 (68,'Salamander','Volcano','Titan',5,8,4,3,2,0,2,0,NULL,NULL,NULL,1,'flamesandfrost',''),
	 (69,'Imp Servant','Volcano','Warden',6,3,6,3,0,5,0,0,NULL,NULL,NULL,0,'flamesandfrost',''),
	 (70,'Demon','Volcano','Boss',7,16,6,6,0,0,0,1,'count area Volcano v 2',NULL,NULL,0,'flamesandfrost','Gain 2 Victory Points for each Volcano Monster you own.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (71,'Yeti','Glacier','Beast',1,6,1,3,0,0,0,1,'choose g 3 m 3',NULL,NULL,0,'flamesandfrost','Gain 3 Gold or 3 Magic.'),
	 (72,'Yeti','Glacier','Beast',2,6,1,3,0,0,0,1,'choose g 3 m 3',NULL,NULL,0,'flamesandfrost','Gain 3 Gold or 3 Magic.'),
	 (73,'Yeti','Glacier','Beast',3,6,1,3,0,0,0,1,'choose g 3 m 3',NULL,NULL,1,'flamesandfrost','Gain 3 Gold or 3 Magic.'),
	 (74,'Ice Giant','Glacier','Titan',4,10,2,3,0,0,0,1,'choose g 6 v 3',NULL,NULL,0,'flamesandfrost','Gain 6 Gold or 3 Victory Points.'),
	 (75,'Ice Giant','Glacier','Titan',5,10,2,3,0,0,0,1,'choose g 6 v 3',NULL,NULL,0,'flamesandfrost','Gain 6 Gold or 3 Victory Points.'),
	 (76,'Shard','Glacier','Warden',6,8,6,5,5,0,0,0,NULL,NULL,NULL,0,'flamesandfrost',''),
	 (77,'Ice Dragon','Glacier','Boss',7,12,12,5,0,0,0,1,'count area Glacier v 2',NULL,NULL,0,'flamesandfrost','Gain 2 Victory Points for each Glacier Monster you own.'),
	 (78,'Warg','Tundra','Beast',1,3,2,1,0,0,0,1,'choose m 3 <citizens where name==Peasant>',NULL,NULL,0,'flamesandfrost','Gain 3 Magic, or take a Peasant.'),
	 (79,'Warg','Tundra','Beast',2,3,2,1,0,0,0,1,'choose m 3 <citizens where name==Peasant>',NULL,NULL,0,'flamesandfrost','Gain 3 Magic, or take a Peasant.'),
	 (80,'Warg','Tundra','Beast',3,3,2,1,0,0,0,1,'choose m 3 <citizens where name==Peasant>',NULL,NULL,0,'flamesandfrost','Gain 3 Magic, or take a Peasant.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (81,'Frost Ogre','Tundra','Titan',4,5,4,3,0,0,0,1,'choose <citizens>',NULL,NULL,0,'flamesandfrost','Take a Citizen.'),
	 (82,'Frost Ogre','Tundra','Titan',5,5,4,3,0,0,0,1,'choose <citizens>',NULL,NULL,1,'flamesandfrost','Take a Citizen.'),
	 (83,'Trapmaster','Tundra','Warden',6,10,0,3,0,0,0,1,'take_owned monster random',NULL,NULL,0,'flamesandfrost','Take a random Monster owned by an opponent.'),
	 (84,'Snow Queen','Tundra','Boss',7,12,5,5,0,0,0,1,'<domains>',NULL,NULL,0,'flamesandfrost','Take a Domain.'),
	 (85,'Mummy','Desert','Minion',1,2,2,2,0,0,0,1,'choose g 2 s 2 m 2',NULL,NULL,0,'flamesandfrost','Gain 2 Wild.'),
	 (86,'Mummy','Desert','Minion',2,2,2,2,0,0,0,1,'choose g 2 s 2 m 2',NULL,NULL,0,'flamesandfrost','Gain 2 Wild.'),
	 (87,'Giant Scorpion','Desert','Beast',3,7,0,3,2,0,1,0,NULL,NULL,NULL,0,'flamesandfrost',''),
	 (88,'Giant Scorpion','Desert','Beast',4,7,0,3,2,0,1,0,NULL,NULL,NULL,0,'flamesandfrost',''),
	 (89,'Giant Scorpion','Desert','Beast',5,7,0,3,2,0,1,0,NULL,NULL,NULL,1,'flamesandfrost',''),
	 (90,'Pharoah','Desert','Warden',6,2,6,3,4,0,0,0,NULL,NULL,NULL,0,'flamesandfrost','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (91,'Sand Wyrm','Desert','Boss',7,15,3,6,0,0,0,1,'choose <count area Desert g 2> <citizens + v 2>',NULL,NULL,0,'flamesandfrost','Gain 2 Gold for each Desert Monster you own, or take a Citizen and gain 2 Victory Points.'),
	 (92,'Ghoul','Oasis','Minion',1,4,0,3,0,0,0,1,'choose g 1 s 1 m 1',NULL,NULL,0,'flamesandfrost','Gain 1 Wild.'),
	 (93,'Ghoul','Oasis','Minion',2,4,0,3,0,0,0,1,'choose g 1 s 1 m 1',NULL,NULL,0,'flamesandfrost','Gain 1 Wild.'),
	 (94,'Ghoul','Oasis','Minion',3,4,0,3,0,0,0,1,'choose g 1 s 1 m 1',NULL,NULL,0,'flamesandfrost','Gain 1 Wild.'),
	 (95,'Ghoul','Oasis','Minion',4,4,0,3,0,0,0,1,'choose g 1 s 1 m 1',NULL,NULL,1,'flamesandfrost','Gain 1 Wild.'),
	 (96,'Cyclops','Oasis','Titan',5,9,3,4,0,0,0,1,'choose g 4 s 4 m 4 v 2',NULL,NULL,0,'flamesandfrost','Gain 4 Wild or 2 Victory Points.'),
	 (97,'Mirage','Oasis','Warden',6,1,10,3,0,0,0,1,'choose g 6 s 6 m 6',NULL,NULL,0,'flamesandfrost','Gain 6 Wild.'),
	 (98,'Efreet','Oasis','Boss',7,10,10,7,0,0,0,1,'choose <count area Oasis g 2> <count area Oasis s 2> <count area Oasis m 2>',NULL,NULL,0,'flamesandfrost','Gain 2 Wild for each Oasis Monster you own.'),
	 (99,'Gnoll Huntmaster','Gnolls','Beast',1,7,0,3,3,0,0,0,NULL,NULL,NULL,0,'gnolls',''),
	 (100,'Gnoll Huntmaster','Gnolls','Beast',2,7,0,3,3,0,0,0,NULL,NULL,NULL,1,'gnolls','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (101,'Gnolls','Gnolls','Beast',3,9,0,3,0,0,0,1,'choose <citizens>',NULL,NULL,0,'gnolls','Take a Citizen.'),
	 (102,'Gnolls','Gnolls','Beast',4,9,0,3,0,0,0,1,'choose <citizens>',NULL,NULL,0,'gnolls','Take a Citizen.'),
	 (103,'Gnolls','Gnolls','Beast',5,9,0,3,0,0,0,1,'choose <citizens>',NULL,NULL,0,'gnolls','Take a Citizen.'),
	 (104,'Gnoll Bonewitch','Gnolls','Warden',6,3,2,2,0,0,0,1,'banish_center citizen + choose <citizens>',NULL,NULL,0,'gnolls','Banish a face-up Citizen from the center stacks, then take a Citizen.'),
	 (105,'Gnoll Pack Lord','Gnolls','Boss',7,9,1,4,0,0,0,1,'choose <count area Gnolls g 1> <citizens>',NULL,NULL,0,'gnolls','Gain 1 Gold for each Gnolls Monster you own, or take a Citizen.'),
	 (106,'Dire Rat','Sewer','Beast',1,1,1,1,0,0,0,1,'choose g 2 s 2 m 2',NULL,NULL,0,'shadowvale','Gain 2 Wild.'),
	 (107,'Dire Rat','Sewer','Beast',2,1,1,1,0,0,0,1,'choose g 2 s 2 m 2',NULL,NULL,0,'shadowvale','Gain 2 Wild.'),
	 (108,'Dire Rat','Sewer','Beast',3,1,1,1,0,0,0,1,'choose g 2 s 2 m 2',NULL,NULL,1,'shadowvale','Gain 2 Wild.'),
	 (109,'Crocodile','Sewer','Titan',4,4,0,2,2,0,0,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (110,'Crocodile','Sewer','Titan',5,4,0,2,2,0,0,0,NULL,NULL,NULL,0,'shadowvale','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (111,'Creature','Sewer','Warden',6,6,0,3,3,0,0,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (112,'Rat King','Sewer','Boss',7,6,2,4,0,0,0,1,'count area Sewer g 1',NULL,NULL,0,'shadowvale','Gain 1 Gold for each Sewer Monster you own.'),
	 (113,'Zombies','Necropolis','Minion',1,2,0,2,0,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (114,'Zombies','Necropolis','Minion',2,2,0,2,0,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (115,'Zombies','Necropolis','Minion',3,2,0,2,0,0,1,0,NULL,NULL,NULL,1,'shadowvale',''),
	 (116,'Hounds','Necropolis','Beast',4,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (117,'Hounds','Necropolis','Beast',5,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (118,'Harrier','Necropolis','Warden',6,7,0,4,0,0,3,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (119,'Undead Giant','Necropolis','Boss',7,10,0,5,0,0,0,1,'count area Necropolis g 1',NULL,NULL,0,'shadowvale','Gain 1 Gold for each Necropolis Monster you own.'),
	 (120,'Banshee','Woods','Minion',1,3,1,2,0,0,2,0,NULL,NULL,NULL,0,'shadowvale','');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (121,'Banshee','Woods','Minion',2,3,1,2,0,0,2,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (122,'Banshee','Woods','Minion',3,3,1,2,0,0,2,0,NULL,NULL,NULL,1,'shadowvale',''),
	 (123,'Sasquatch','Woods','Beast',4,7,0,2,2,0,3,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (124,'Sasquatch','Woods','Beast',5,7,0,2,2,0,3,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (125,'Wendigo','Woods','Warden',6,10,3,5,0,0,0,1,'choose <citizens>',NULL,NULL,0,'shadowvale','Take a Citizen.'),
	 (126,'Ghost Witch','Woods','Boss',7,14,6,6,0,0,0,1,'count area Woods m 2',NULL,NULL,0,'shadowvale','Gain 2 Magic for each Woods Monster you own.'),
	 (127,'Werewolf','Den','Beast',1,4,0,1,0,0,0,1,'choose g 3 m 3',NULL,NULL,0,'shadowvale','Gain 3 Gold or 3 Magic.'),
	 (128,'Werewolf','Den','Beast',2,4,0,1,0,0,0,1,'choose g 3 m 3',NULL,NULL,0,'shadowvale','Gain 3 Gold or 3 Magic.'),
	 (129,'Werewolf','Den','Beast',3,4,0,1,0,0,0,1,'choose g 3 m 3',NULL,NULL,1,'shadowvale','Gain 3 Gold or 3 Magic.'),
	 (130,'Volgya','Den','Titan',4,7,1,3,0,0,0,1,'choose v 2 <citizens where name==Knight>',NULL,NULL,0,'shadowvale','Gain 2 Victory Points, or take a Knight.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (131,'Volgya','Den','Titan',5,7,1,3,0,0,0,1,'choose v 2 <citizens where name==Knight>',NULL,NULL,0,'shadowvale','Gain 2 Victory Points, or take a Knight.'),
	 (132,'Lycan Mage','Den','Warden',6,2,7,3,0,5,0,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (133,'Alpha','Den','Boss',7,12,4,7,0,0,0,1,'choose <count area Den g 2> <citizens + v 1>',NULL,NULL,0,'shadowvale','Gain 2 Gold for each Den Monster you own, or take a Citizen and gain 1 Victory Point.'),
	 (134,'Vampire','Crypt','Minion',1,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (135,'Vampire','Crypt','Minion',2,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (136,'Vampire','Crypt','Minion',3,5,0,3,1,0,1,0,NULL,NULL,NULL,1,'shadowvale',''),
	 (137,'Darkstalker','Crypt','Titan',4,8,0,3,2,0,2,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (138,'Darkstalker','Crypt','Titan',5,8,0,3,2,0,2,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (139,'Nosferatu','Crypt','Warden',6,12,2,5,0,0,6,0,NULL,NULL,NULL,0,'shadowvale',''),
	 (140,'Vampire King','Crypt','Boss',7,16,4,7,0,0,0,1,'count area Crypt v 1',NULL,NULL,0,'shadowvale','Gain 1 Victory Point for each Crypt Monster you own.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (141,'Araby Brigands','Cutthroats','Titan',1,2,1,1,0,0,0,1,'count owned_monster_name "Araby Brigands" v 1',1,'count owned_monster_name "Araby Brigands" s 1 + count owned_monster_name "Araby Brigands" m 1',0,'crimsonseas','Gain 1 Victory Point for each Araby Brigands you own.'),
	 (142,'Araby Brigands','Cutthroats','Titan',2,2,1,1,0,0,0,1,'count owned_monster_name "Araby Brigands" v 1',1,'count owned_monster_name "Araby Brigands" s 1 + count owned_monster_name "Araby Brigands" m 1',0,'crimsonseas','Gain 1 Victory Point for each Araby Brigands you own.'),
	 (143,'Araby Brigands','Cutthroats','Titan',3,2,1,1,0,0,0,1,'count owned_monster_name "Araby Brigands" v 1',1,'count owned_monster_name "Araby Brigands" s 1 + count owned_monster_name "Araby Brigands" m 1',0,'crimsonseas','Gain 1 Victory Point for each Araby Brigands you own.'),
	 (144,'Araby Brigands','Cutthroats','Titan',4,2,1,1,0,0,0,1,'count owned_monster_name "Araby Brigands" v 1',1,'count owned_monster_name "Araby Brigands" s 1 + count owned_monster_name "Araby Brigands" m 1',0,'crimsonseas','Gain 1 Victory Point for each Araby Brigands you own.'),
	 (145,'Araby Brigands','Cutthroats','Titan',5,2,1,1,0,0,0,1,'count owned_monster_name "Araby Brigands" v 1',1,'count owned_monster_name "Araby Brigands" s 1 + count owned_monster_name "Araby Brigands" m 1',1,'crimsonseas','Gain 1 Victory Point for each Araby Brigands you own.'),
	 (146,'Amarynth Marauders','Cutthroats','Warden',6,7,2,4,0,0,0,1,'choose <citizens where name==Peasant> <citizens where name==Knight>',0,NULL,0,'crimsonseas','Take a Peasant, or take a Knight.'),
	 (147,'Gargan Soul Hunters','Cutthroats','Boss',7,10,8,6,0,0,0,1,'choose <citizens 3> <noble>',0,NULL,0,'crimsonseas','Gain 3 Citizens or 1 Noble.'),
	 (148,'Goblin Pirates','Dark Waters','Minion',1,3,0,1,0,0,0,1,'count owned_monster_name "Goblin Pirates" g 3',1,'count owned_monster_name "Goblin Pirates" s 1',0,'crimsonseas','Gain 3 Gold for each Goblin Pirates you own.'),
	 (149,'Goblin Pirates','Dark Waters','Minion',2,3,0,1,0,0,0,1,'count owned_monster_name "Goblin Pirates" g 3',1,'count owned_monster_name "Goblin Pirates" s 1',0,'crimsonseas','Gain 3 Gold for each Goblin Pirates you own.'),
	 (150,'Goblin Pirates','Dark Waters','Minion',3,3,0,1,0,0,0,1,'count owned_monster_name "Goblin Pirates" g 3',1,'count owned_monster_name "Goblin Pirates" s 1',0,'crimsonseas','Gain 3 Gold for each Goblin Pirates you own.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (151,'Goblin Pirates','Dark Waters','Minion',4,3,0,1,0,0,0,1,'count owned_monster_name "Goblin Pirates" g 3',1,'count owned_monster_name "Goblin Pirates" s 1',0,'crimsonseas','Gain 3 Gold for each Goblin Pirates you own.'),
	 (152,'Goblin Pirates','Dark Waters','Minion',5,3,0,1,0,0,0,1,'count owned_monster_name "Goblin Pirates" g 3',1,'count owned_monster_name "Goblin Pirates" s 1',1,'crimsonseas','Gain 3 Gold for each Goblin Pirates you own.'),
	 (153,'Orc Raiders','Dark Waters','Warden',6,10,0,6,0,0,0,1,'choose g 4 p 2',0,NULL,0,'crimsonseas','Gain 4 Gold or 2 Maps.'),
	 (154,'Dragonkin Ravagers','Dark Waters','Boss',7,15,2,6,0,0,0,1,'count type Minion g 3',0,NULL,0,'crimsonseas','Gain 3 Gold for each owned Minion.'),
	 (155,'Sea Drake','Gloom Gyre','Beast',1,1,2,2,0,0,0,1,'count owned_monster_name "Sea Drake" s 3',1,'count owned_monster_name "Sea Drake" m 1',0,'crimsonseas','Gain 3 Strength for each Sea Drake you own.'),
	 (156,'Sea Drake','Gloom Gyre','Beast',2,1,2,2,0,0,0,1,'count owned_monster_name "Sea Drake" s 3',1,'count owned_monster_name "Sea Drake" m 1',0,'crimsonseas','Gain 3 Strength for each Sea Drake you own.'),
	 (157,'Sea Drake','Gloom Gyre','Beast',3,1,2,2,0,0,0,1,'count owned_monster_name "Sea Drake" s 3',1,'count owned_monster_name "Sea Drake" m 1',0,'crimsonseas','Gain 3 Strength for each Sea Drake you own.'),
	 (158,'Sea Drake','Gloom Gyre','Beast',4,1,2,2,0,0,0,1,'count owned_monster_name "Sea Drake" s 3',1,'count owned_monster_name "Sea Drake" m 1',0,'crimsonseas','Gain 3 Strength for each Sea Drake you own.'),
	 (159,'Sea Drake','Gloom Gyre','Beast',5,1,2,2,0,0,0,1,'count owned_monster_name "Sea Drake" s 3',1,'count owned_monster_name "Sea Drake" m 1',1,'crimsonseas','Gain 3 Strength for each Sea Drake you own.'),
	 (160,'Water Elemental','Gloom Gyre','Warden',6,3,9,4,3,0,0,1,'<domains>',0,NULL,0,'crimsonseas','Take a Domain.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (161,'Storm Dragon','Gloom Gyre','Boss',7,14,14,7,0,0,0,1,'count area "Gloom Gyre" v 2',0,NULL,0,'crimsonseas','Gain 2 Victory Points for each Gloom Gyre Monster you own.'),
	 (162,'Harpies','Skerry','Beast',1,3,1,2,0,0,0,1,'choose <count owned_monster_name "Harpies" g 2> <count owned_monster_name "Harpies" s 2> <count owned_monster_name "Harpies" m 2>',1,'count owned_monster_name "Harpies" m 1',0,'crimsonseas','Gain 2 Wild for each Harpies you own.'),
	 (163,'Harpies','Skerry','Beast',2,3,1,2,0,0,0,1,'choose <count owned_monster_name "Harpies" g 2> <count owned_monster_name "Harpies" s 2> <count owned_monster_name "Harpies" m 2>',1,'count owned_monster_name "Harpies" m 1',0,'crimsonseas','Gain 2 Wild for each Harpies you own.'),
	 (164,'Harpies','Skerry','Beast',3,3,1,2,0,0,0,1,'choose <count owned_monster_name "Harpies" g 2> <count owned_monster_name "Harpies" s 2> <count owned_monster_name "Harpies" m 2>',1,'count owned_monster_name "Harpies" m 1',0,'crimsonseas','Gain 2 Wild for each Harpies you own.'),
	 (165,'Harpies','Skerry','Beast',4,3,1,2,0,0,0,1,'choose <count owned_monster_name "Harpies" g 2> <count owned_monster_name "Harpies" s 2> <count owned_monster_name "Harpies" m 2>',1,'count owned_monster_name "Harpies" m 1',0,'crimsonseas','Gain 2 Wild for each Harpies you own.'),
	 (166,'Harpies','Skerry','Beast',5,3,1,2,0,0,0,1,'choose <count owned_monster_name "Harpies" g 2> <count owned_monster_name "Harpies" s 2> <count owned_monster_name "Harpies" m 2>',1,'count owned_monster_name "Harpies" m 1',1,'crimsonseas','Gain 2 Wild for each Harpies you own.'),
	 (167,'Ostrakon','Skerry','Warden',6,6,2,4,0,0,0,1,'choose g 4 s 4 m 4 t 1',0,NULL,0,'crimsonseas','Gain 4 Wild or 1 Tome.'),
	 (168,'Wereshark','Skerry','Boss',7,12,5,6,0,0,0,1,'choose <count type Beast g 2> <count type Beast s 2> <count type Beast m 2>',0,NULL,0,'crimsonseas','Gain 2 Wild for each owned Beast.'),
	 (169,'Bryne','The Deep','Beast',1,1,1,1,0,0,0,1,'choose g 2 p 1',1,'count owned_monster_name "Bryne" s 1',0,'crimsonseas','Gain 2 Gold or 1 Map.'),
	 (170,'Bryne','The Deep','Beast',2,1,1,1,0,0,0,1,'choose g 2 p 1',1,'count owned_monster_name "Bryne" s 1',0,'crimsonseas','Gain 2 Gold or 1 Map.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (171,'Bryne','The Deep','Beast',3,1,1,1,0,0,0,1,'choose g 2 p 1',1,'count owned_monster_name "Bryne" s 1',0,'crimsonseas','Gain 2 Gold or 1 Map.'),
	 (172,'Bryne','The Deep','Beast',4,1,1,1,0,0,0,1,'choose g 2 p 1',1,'count owned_monster_name "Bryne" s 1',0,'crimsonseas','Gain 2 Gold or 1 Map.'),
	 (173,'Bryne','The Deep','Beast',5,1,1,1,0,0,0,1,'choose g 2 p 1',1,'count owned_monster_name "Bryne" s 1',1,'crimsonseas','Gain 2 Gold or 1 Map.'),
	 (174,'Sea Witch','The Deep','Warden',6,2,10,5,0,0,0,1,'choose g 6 s 6 m 6',0,NULL,0,'crimsonseas','Gain 6 Wild.'),
	 (175,'Kraken','The Deep','Boss',7,16,3,6,0,0,0,1,'count area "The Deep" v 2',0,NULL,0,'crimsonseas','Gain 2 Victory Points for each Monster you own in The Deep.'),
	 (176,'Kaharian Hatchlings','Kaharian','Minion',1,5,0,2,0,0,0,1,'choose g 3 <citizens where name==Peasant>',NULL,NULL,0,'kaharian','Gain 3 Gold, or take a Peasant.'),
	 (177,'Kaharian Hatchlings','Kaharian','Minion',2,5,0,2,0,0,0,1,'choose g 3 <citizens where name==Peasant>',NULL,NULL,0,'kaharian','Gain 3 Gold, or take a Peasant.'),
	 (178,'Kaharian Hatchlings','Kaharian','Minion',3,5,0,2,0,0,0,1,'choose g 3 <citizens where name==Peasant>',NULL,NULL,1,'kaharian','Gain 3 Gold, or take a Peasant.'),
	 (179,'Kaharian Brute','Kaharian','Titan',4,9,0,2,2,0,0,1,'<citizens>',NULL,NULL,0,'kaharian','Take a Citizen.'),
	 (180,'Kaharian Brute','Kaharian','Titan',5,9,0,2,2,0,0,1,'<citizens>',NULL,NULL,0,'kaharian','Take a Citizen.');
INSERT INTO vckonline.monsters (id_monsters,name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion,special_reward_text) VALUES
	 (181,'Kaharian Hunt Mage','Kaharian','Warden',6,5,6,0,0,0,0,1,'<citizens> + <domains>',NULL,NULL,0,'kaharian','Take a Citizen, then take a Domain.'),
	 (182,'Kaharian Kill Master','Kaharian','Boss',7,10,2,5,0,0,0,1,'choose <count area Kaharian m 1> <citizens>',NULL,NULL,0,'kaharian','Gain 1 Magic for each Kaharian Monster you own, or take a Citizen.'),
	 (183,'Hell Wasp','Fire Temple','Beast',1,2,7,3,0,0,0,1,'choose g 3 m 3',0,NULL,0,'firetemple','Gain 3 Gold or 3 Magic.'),
	 (184,'Hell Wasp','Fire Temple','Beast',2,2,7,3,0,0,0,1,'choose g 3 m 3',0,NULL,0,'firetemple','Gain 3 Gold or 3 Magic.'),
	 (185,'Hell Wasp','Fire Temple','Beast',3,2,7,3,0,0,0,1,'choose g 3 m 3',0,NULL,1,'firetemple','Gain 3 Gold or 3 Magic.'),
	 (186,'Gagambah','Fire Temple','Beast',4,9,5,4,3,0,3,0,NULL,0,NULL,0,'firetemple',''),
	 (187,'Gagambah','Fire Temple','Beast',5,9,5,4,3,0,3,0,NULL,0,NULL,0,'firetemple',''),
	 (188,'Sigbin','Fire Temple','Warden',6,4,10,5,0,0,0,1,'choose g 4 v 2',0,NULL,0,'firetemple','Gain 4 Gold or 2 Victory Points.'),
	 (189,'Lava Elemental','Fire Temple','Boss',7,11,11,6,0,0,0,1,'count area "Fire Temple" v 2',0,NULL,0,'firetemple','Gain 2 Victory Points for each Fire Temple Monster you own.');
