INSERT INTO `vckonline`.`starters`
(`name`,
`roll_match1`,
`roll_match2`,
`gold_payout_on_turn`,
`gold_payout_off_turn`,
`strength_payout_on_turn`,
`strength_payout_off_turn`,
`magic_payout_on_turn`,
`magic_payout_off_turn`,
`has_special_payout_on_turn`,
`has_special_payout_off_turn`,
`special_payout_on_turn`,
`special_payout_off_turn`,
`activation_trigger`)
VALUES
('Peasant',/*name*/
5,/*roll_match1*/
0,/*roll_match2*/
1,/*gold_payout_on_turn*/
1,/*gold_payout_off_turn*/
0,/*strength_payout_on_turn*/
0,/*strength_payout_off_turn*/
0,/*magic_payout_on_turn*/
0,/*magic_payout_off_turn*/
0,/*has_special_payout_on_turn*/
0,/*has_special_payout_off_turn*/
0,/*special_payout_on_turn*/
0,/*special_payout_off_turn*/
''/*activation_trigger*/);
