INSERT INTO `vckonline`.`dukes`
(`name`,
`gold_mult`,
`strength_mult`,
`magic_mult`,
`shadow_mult`,
`holy_mult`,
`soldier_mult`,
`worker_mult`,
`monster_mult`,
`citizen_mult`,
`domain_mult`,
`boss_mult`,
`minion_mult`,
`beast_mult`,
`titan_mult`)
VALUES
('',/*name*/
,/*gold_mult*/
,/*strength_mult*/
,/*magic_mult*/
,/*shadow_mult*/
,/*holy_mult*/
,/*soldier_mult*/
,/*worker_mult*/
,/*monster_mult*/
,/*citizen_mult*/
,/*domain_mult*/
,/*boss_mult*/
,/*minion_mult*/
,/*beast_mult*/
/*titan_mult*/);
