INSERT INTO `vckonline`.`citizens`
(`name`,
`gold_cost`,
`roll_match1`,
`roll_match2`,
`shadow_count`,
`holy_count`,
`soldier_count`,
`worker_count`,
`gold_payout_on_turn`,
`gold_payout_off_turn`,
`strength_payout_on_turn`,
`strength_payout_off_turn`,
`magic_payout_on_turn`,
`magic_payout_off_turn`,
`has_special_payout_on_turn`,
`has_special_payout_off_turn`,
`special_payout_on_turn`,
`special_payout_off_turn`,
`special_citizen`)
VALUES
('',/*name*/
,/*gold_cost*/
,/*roll_match1*/
,/*roll_match2*/
,/*shadow_count*/
,/*holy_count*/
,/*soldier_count*/
,/*worker_count*/
,/*gold_payout_on_turn*/
,/*gold_payout_off_turn*/
,/*strength_payout_on_turn*/
,/*strength_payout_off_turn*/
,/*magic_payout_on_turn*/
,/*magic_payout_off_turn*/
,/*has_special_payout_on_turn*/
,/*has_special_payout_off_turn*/
,/*special_payout_on_turn*/
,/*special_payout_off_turn*/
/*special_citizen*/);
