INSERT INTO `vckonline`.`nobles`
(`name`,
`expansion`,
`shadow_count`,
`holy_count`,
`soldier_count`,
`worker_count`,
`shadow_multiplier`,
`holy_multiplier`,
`soldier_multiplier`,
`worker_multiplier`,
`monster_multiplier`,
`citizen_multiplier`,
`domain_multiplier`,
`boss_multiplier`,
`minion_multiplier`,
`beast_multiplier`,
`titan_multiplier`,
`goods_multiplier`,
`has_special_duke_payout`,
`special_duke_payout`)
VALUES
('',/*name*/
'base',/*expansion*/
,/*shadow_count*/
,/*holy_count*/
,/*soldier_count*/
,/*worker_count*/
,/*shadow_multiplier*/
,/*holy_multiplier*/
,/*soldier_multiplier*/
,/*worker_multiplier*/
,/*monster_multiplier*/
,/*citizen_multiplier*/
,/*domain_multiplier*/
,/*boss_multiplier*/
,/*minion_multiplier*/
,/*beast_multiplier*/
,/*titan_multiplier*/
,/*goods_multiplier*/
,/*has_special_duke_payout*/
/*special_duke_payout*/);
