INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Goblin','Hills','Minion',1,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1'),
	 ('Goblin','Hills','Minion',2,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1'),
	 ('Goblin','Hills','Minion',3,1,0,1,1,0,0,0,NULL,NULL,NULL,0,'base1'),
	 ('Goblin Mage','Hills','Titan',4,3,0,2,0,0,0,1,'choose g 1 m 1',NULL,NULL,0,'base1'),
	 ('Goblin Bomber','Hills','Warden',6,5,0,3,0,0,0,1,'choose g 2 m 2  s 2',NULL,NULL,0,'base1'),
	 ('Goblin King','Hills','Boss',7,6,0,4,0,0,0,1,'count area Hills g 1',NULL,NULL,0,'base1'),
	 ('Goblin Mage','Hills','Titan',5,3,0,2,0,0,0,1,'choose g 1 m 1',NULL,NULL,1,'base1'),
	 ('Skeleton','Ruins','Minion',1,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1'),
	 ('Skeleton','Ruins','Minion',2,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1'),
	 ('Skeleton','Ruins','Minion',3,2,0,2,1,0,0,0,NULL,NULL,NULL,0,'base1');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Flaming Skeleton','Ruins','Titan',4,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'base1'),
	 ('Flaming Skeleton','Ruins','Titan',5,5,0,3,1,0,1,0,NULL,NULL,NULL,1,'base1'),
	 ('Death Knight','Ruins','Warden',6,7,0,1,0,0,5,0,NULL,NULL,NULL,0,'base1'),
	 ('Skeleton King','Ruins','Boss',7,8,0,4,0,0,0,1,'count area Ruins g 2',NULL,NULL,0,'base1'),
	 ('Treant','Forest','Minion',1,3,0,1,1,0,1,0,NULL,NULL,NULL,0,'base1'),
	 ('Treant','Forest','Minion',2,3,0,1,1,0,1,0,NULL,NULL,NULL,0,'base1'),
	 ('Treant','Forest','Minion',3,3,0,1,1,0,1,0,NULL,NULL,NULL,1,'base1'),
	 ('Bane Spider','Forest','Beast',4,6,0,2,0,0,0,1,'choose g 3 <citizens where name==Knight>',NULL,NULL,0,'base1'),
	 ('Bane Spider','Forest','Beast',5,6,0,2,0,0,0,1,'choose g 3 <citizens where name==Knight>',NULL,NULL,0,'base1'),
	 ('Ettercap','Forest','Warden',6,3,5,2,0,0,0,1,'choose <citizens where gold_cost<=2>',NULL,NULL,0,'base1');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Spider Queen','Forest','Boss',7,10,3,5,0,0,0,1,'choose <count area Forest g 2> <citizens + v 1>',NULL,NULL,0,'base1'),
	 ('Owlbear','Valley','Beast',1,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1'),
	 ('Owlbear','Valley','Beast',2,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1'),
	 ('Owlbear','Valley','Beast',3,4,0,2,0,0,2,0,NULL,NULL,NULL,0,'base1'),
	 ('Giant','Valley','Titan',4,8,0,3,1,0,2,0,NULL,NULL,NULL,0,'base1'),
	 ('Giant','Valley','Titan',5,8,0,3,1,0,2,0,NULL,NULL,NULL,1,'base1'),
	 ('Satyr Mage','Valley','Warden',6,5,5,3,0,0,0,1,'choose g 5 m 5 s 5',NULL,NULL,0,'base1'),
	 ('Troll','Valley','Boss',7,12,0,6,0,0,0,1,'count area Valley m 2',NULL,NULL,0,'base1'),
	 ('Dire Bear','Mountain','Beast',1,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,0,'base1'),
	 ('Dire Bear','Mountain','Beast',2,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,0,'base1');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Dire Bear','Mountain','Beast',3,5,0,3,0,0,0,1,'choose g 2 m 2',NULL,NULL,1,'base1'),
	 ('Orc Warrior','Mountain','Minion',4,9,0,3,0,0,0,1,'choose <citizens where gold_cost<=3>',NULL,NULL,0,'base1'),
	 ('Orc Warrior','Mountain','Minion',5,9,0,3,0,0,0,1,'choose <citizens where gold_cost<=3>',NULL,NULL,0,'base1'),
	 ('Orc Batrider','Mountain','Warden',6,12,0,5,0,0,0,1,'choose <citizens>',NULL,NULL,0,'base1'),
	 ('Orc Chieftain','Mountain','Boss',7,14,0,6,0,0,0,1,'count area Mountain g 2',NULL,NULL,0,'base1'),
	 ('Gargoyle','Barrens','Minion',1,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2'),
	 ('Gargoyle','Barrens','Minion',2,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2'),
	 ('Gargoyle','Barrens','Minion',3,1,0,1,0,0,1,0,NULL,NULL,NULL,0,'base2'),
	 ('Gargoyle','Barrens','Minion',4,1,0,1,0,0,1,0,NULL,NULL,NULL,1,'base2'),
	 ('Wraith','Barrens','Titan',5,4,3,3,0,0,0,1,NULL,NULL,NULL,0,'base2');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Flesh Golem','Barrens','Warden',6,8,0,1,0,0,5,0,NULL,NULL,NULL,0,'base2'),
	 ('Witch Queen','Barrens','Boss',7,5,4,5,0,0,0,1,NULL,NULL,NULL,0,'base2'),
	 ('Gelatinous Cube','Swamp','Minion',1,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2'),
	 ('Gelatinous Cube','Swamp','Minion',2,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2'),
	 ('Gelatinous Cube','Swamp','Minion',3,4,1,3,2,0,0,0,NULL,NULL,NULL,0,'base2'),
	 ('Gelatinous Cube','Swamp','Minion',4,4,1,3,2,0,0,0,NULL,NULL,NULL,1,'base2'),
	 ('Basilisk','Swamp','Beast',5,6,3,4,0,0,0,1,NULL,NULL,NULL,0,'base2'),
	 ('Swamp Witch','Swamp','Warden',6,1,8,3,0,5,0,0,NULL,NULL,NULL,0,'base2'),
	 ('Swamp Dragon','Swamp','Boss',7,10,4,6,0,0,0,1,NULL,NULL,NULL,0,'base2'),
	 ('Kobolds','Cavern','Minion',1,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Kobolds','Cavern','Minion',2,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2'),
	 ('Kobolds','Cavern','Minion',3,5,1,3,2,0,1,0,NULL,NULL,NULL,0,'base2'),
	 ('Kobolds','Cavern','Minion',4,5,1,3,2,0,1,0,NULL,NULL,NULL,1,'base2'),
	 ('Gold Golem','Cavern','Titan',5,7,3,4,5,0,0,0,NULL,NULL,NULL,0,'base2'),
	 ('Dragonkin','Cavern','Warden',6,6,6,4,3,0,3,0,NULL,NULL,NULL,0,'base2'),
	 ('Red Dragon','Cavern','Boss',7,12,6,7,0,0,0,1,NULL,NULL,NULL,0,'base2'),
	 ('Undead Samurai','Undead Samurai','Minion',1,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai'),
	 ('Undead Samurai','Undead Samurai','Minion',2,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai'),
	 ('Undead Samurai','Undead Samurai','Minion',3,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai'),
	 ('Undead Samurai','Undead Samurai','Minion',4,3,0,1,0,0,3,0,NULL,NULL,NULL,0,'undeadsamurai');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Undead Samurai','Undead Samurai','Minion',5,3,0,1,0,0,3,0,NULL,NULL,NULL,1,'undeadsamurai'),
	 ('Undead Samurai Lord','Undead Samurai','Boss',7,5,5,4,0,0,0,1,NULL,NULL,NULL,0,'undeadsamurai'),
	 ('Lava Hound','Volcano','Beast',1,7,1,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Lava Hound','Volcano','Beast',2,7,1,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Lava Hound','Volcano','Beast',3,7,1,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Salamander','Volcano','Titan',4,8,4,3,2,0,2,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Salamander','Volcano','Titan',5,8,4,3,2,0,2,0,NULL,NULL,NULL,1,'flamesandfrost'),
	 ('Imp Servant','Volcano','Warden',6,3,6,3,0,5,0,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Demon','Volcano','Boss',7,16,6,6,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Yeti','Glacier','Beast',1,6,1,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Yeti','Glacier','Beast',2,6,1,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Yeti','Glacier','Beast',3,6,1,3,0,0,0,1,NULL,NULL,NULL,1,'flamesandfrost'),
	 ('Ice Giant','Glacier','Titan',4,10,2,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Ice Giant','Glacier','Titan',5,10,2,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Shard','Glacier','Warden',6,8,6,5,5,0,0,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Ice Dragon','Glacier','Boss',7,12,12,5,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Warg','Tundra','Beast',1,3,2,1,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Warg','Tundra','Beast',2,3,2,1,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Warg','Tundra','Beast',3,3,2,1,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Frost Ogre','Tundra','Titan',4,5,4,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Trapmaster','Tundra','Warden',6,10,0,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Snow Queen','Tundra','Boss',7,12,5,5,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Mummy','Desert','Minion',1,2,2,2,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Mummy','Desert','Minion',2,2,2,2,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Giant Scorpion','Desert','Beast',3,7,0,3,2,0,1,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Giant Scorpion','Desert','Beast',4,7,0,3,2,0,1,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Giant Scorpion','Desert','Beast',5,7,0,3,2,0,1,0,NULL,NULL,NULL,1,'flamesandfrost'),
	 ('Pharoah','Desert','Warden',6,2,6,3,4,0,0,0,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Sand Wyrm','Desert','Boss',7,15,3,6,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Ghoul','Oasis','Minion',1,4,0,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Ghoul','Oasis','Minion',2,4,0,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Ghoul','Oasis','Minion',3,4,0,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Ghoul','Oasis','Minion',4,4,0,3,0,0,0,1,NULL,NULL,NULL,1,'flamesandfrost'),
	 ('Cyclops','Oasis','Titan',5,9,3,4,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Mirage','Oasis','Warden',6,1,10,3,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Efreet','Oasis','Boss',7,10,10,7,0,0,0,1,NULL,NULL,NULL,0,'flamesandfrost'),
	 ('Gnoll Huntmaster','Knolls','Beast',1,7,0,3,3,0,0,0,NULL,NULL,NULL,0,'gnolls'),
	 ('Gnoll Huntmaster','Knolls','Beast',2,7,0,3,3,0,0,0,NULL,NULL,NULL,1,'gnolls'),
	 ('Gnolls','Knolls','Beast',3,9,0,3,0,0,0,1,NULL,NULL,NULL,0,'gnolls'),
	 ('Gnolls','Knolls','Beast',4,9,0,3,0,0,0,1,NULL,NULL,NULL,0,'gnolls');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Gnolls','Knolls','Beast',5,9,0,3,0,0,0,1,NULL,NULL,NULL,0,'gnolls'),
	 ('Gnoll Bonewitch','Knolls','Warden',6,3,2,2,0,0,0,1,NULL,NULL,NULL,0,'gnolls'),
	 ('Gnoll Packlord','Knolls','Boss',7,9,1,4,0,0,0,1,NULL,NULL,NULL,0,'gnolls'),
	 ('Dire Rat','Sewer','Beast',1,1,1,1,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Dire Rat','Sewer','Beast',2,1,1,1,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Dire Rat','Sewer','Beast',3,1,1,1,0,0,0,1,NULL,NULL,NULL,1,'shadowvale'),
	 ('Crocodile','Sewer','Titan',4,4,0,2,2,0,0,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Crocodile','Sewer','Titan',5,4,0,2,2,0,0,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Creature','Sewer','Warden',6,6,0,3,3,0,0,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Rat King','Sewer','Boss',7,8,2,4,0,0,0,1,NULL,NULL,NULL,0,'shadowvale');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Zombies','Necropolis','Minion',1,2,0,2,0,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Zombies','Necropolis','Minion',2,2,0,2,0,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Zombies','Necropolis','Minion',3,2,0,2,0,0,1,0,NULL,NULL,NULL,1,'shadowvale'),
	 ('Hounds','Necropolis','Beast',4,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Hounds','Necropolis','Beast',5,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Harrier','Necropolis','Warden',6,7,0,4,0,0,3,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Undead Giant','Necropolis','Boss',7,10,0,5,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Banshee','Woods','Minion',1,3,1,2,0,0,2,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Banshee','Woods','Minion',2,3,1,2,0,0,2,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Banshee','Woods','Minion',3,3,1,2,0,0,2,0,NULL,NULL,NULL,1,'shadowvale');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Sasquatch','Woods','Beast',4,7,0,2,2,0,3,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Sasquatch','Woods','Beast',5,7,0,2,2,0,3,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Wendigo','Woods','Warden',6,10,3,5,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Ghost Witch','Woods','Boss',7,14,6,6,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Werewolf','Den','Beast',1,4,0,1,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Werewolf','Den','Beast',2,4,0,1,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Werewolf','Den','Beast',3,4,0,1,0,0,0,1,NULL,NULL,NULL,1,'shadowvale'),
	 ('Volgya','Den','Titan',4,7,1,3,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Volgya','Den','Titan',5,7,1,3,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Lycan Mage','Den','Warden',6,2,7,3,0,5,0,0,NULL,NULL,NULL,0,'shadowvale');
INSERT INTO vckonline.monsters (name,area,`monster_type`,`monster_order`,strength_cost,magic_cost,vp_reward,gold_reward,strength_reward,magic_reward,has_special_reward,special_reward,has_special_cost,special_cost,is_extra,expansion) VALUES
	 ('Alpha','Den','Boss',7,12,4,7,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Vampire','Crypt','Minion',1,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Vampire','Crypt','Minion',2,5,0,3,1,0,1,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Vampire','Crypt','Minion',3,5,0,3,1,0,1,0,NULL,NULL,NULL,1,'shadowvale'),
	 ('Darkstalker','Crypt','Titan',4,8,0,3,2,0,2,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Darkstalker','Crypt','Titan',5,8,0,3,2,0,2,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Nosferatu','Crypt','Warden',6,12,2,5,0,0,6,0,NULL,NULL,NULL,0,'shadowvale'),
	 ('Vampire King','Crypt','Boss',7,16,4,7,0,0,0,1,NULL,NULL,NULL,0,'shadowvale'),
	 ('Undead Samurai Rider','Undead Samurai','Warden',6,3,3,3,0,0,0,1,NULL,NULL,NULL,0,'undeadsamurai'),
	 ('Frost Ogre','Tundra','Titan',5,5,4,3,0,0,0,0,NULL,NULL,NULL,1,'flamesandfrost');
